export const PROFILE_GET_DETAILS = 'PROFILE_GET_DETAILS';
export const PROFILE_GET_DETAILS_REQUEST = 'PROFILE_GET_DETAILS_REQUEST';

export const GET_FAVOURITE_MOVIES = 'GET_FAVOURITE_MOVIES';
export const GET_FAVOURITE_MOVIES_REQUEST = 'GET_FAVOURITE_MOVIES_REQUEST';

export const GET_FAVOURITE_TVS = 'GET_FAVOURITE_TVS';
export const GET_FAVOURITE_TVS_REQUEST = 'GET_FAVOURITE_TVS_REQUEST';