export const POST_FAVOURITE_SHOW = 'POST_FAVOURITE_SHOW';
export const POST_FAVOURITE_SHOW_REQUEST = 'POST_FAVOURITE_SHOW_REQUEST';

export const POST_MOVIE_TO_WATCHLIST = 'POST_MOVIE_TO_WATCHLIST';
export const POST_MOVIE_TO_WATCHLIST_REQUEST = 'POST_MOVIE_TO_WATCHLIST_REQUEST';